### ISSUE TITLE
部分应用在拉起其他应用授权时弹出的对话框会拦截授权，变成普通的启动应用

### ISSUE THREAD

**Issue by jhll1124** [Xposed-Modules-Repo/com.alphi.actvityopenmanager#10]
如题，我发现的是咸鱼拉起淘宝

**Comment by alphime** [comment]
闲鱼会进入闲鱼内置浏览器的淘宝网页版，并不是打开淘宝应用，经过测试不存在拦截无效！

**Comment by jhll1124** [comment]
麻烦你升到最新版的，再重新测试一下。我在禁用了模块之后可以正常拉起淘宝，但是启用的不行。而且我说这只是其中一个例子，还有其他很多情况，不能正常使用。我们作为用户没有要求开发者必须作出适配，你说懒不更新我们都不会责备，但是以这种理由作为搪塞，我觉得是不合适的。

**Comment by alphime** [comment]
我需要您提供的录制视频和模块日志，可否提供下？

**Comment by jhll1124** [comment]
https://github.com/user-attachments/assets/0ed7c171-b1e6-41ad-bb08-0d285481830b

**Comment by alphime** [comment]
> Screenrecorder-2024-12-22-18-51-39-407.mp4

你可以加入规则 `allow * A:com.taobao.android.auth.AuthEntranceActivity`

**Comment by jhll1124** [comment]
目前就是这么用的
