### ISSUE TITLE
规则疑问

### ISSUE THREAD

**Issue by wyfang** [Xposed-Modules-Repo/com.alphi.actvityopenmanager#4]
我在chrome访问一些网站，它们会弹安装，然后在桌面上会有一个图标，点击也会提示是否允许，我复制了包名并添加了规则：
allow * org.chromium.chrome.browser.webapps.WebappLauncherActivity

但依然会弹。以及无论是否有规则和点击同意，都大概率打不开，表现上看起来像来不及点同意或拒绝，已经打开失败了。

**Comment by alphime** [comment]
改成
`allow * A:org.chromium.chrome.browser.webapps.WebappLauncherActivity`
