### ISSUE TITLE
那次将说明文字设置为可换行，或可复制

### ISSUE THREAD

**Issue by iaston** [Xposed-Modules-Repo/com.alphi.actvityopenmanager#5]
![QQ_1730194766772](https://github.com/user-attachments/assets/c2eb75a1-cbc2-4afb-8da2-c1e87e5f243f)

看规则说明时，不能自动换行，看的时候要横着拉好多次，想着复制下来在其它APP中看也行，结果又不能复制。使用了手机横屏也不能完全显示所有的内容。

建议把说明文字设置为自动换行，或允许复制。

**Comment by alphime** [comment]
你可以从保留规则里面复制修改

**Comment by iaston** [comment]
我是指最上面的那个帮助内容，我想跟着学，就要看很多次呢。不过，现在我已经看完了，所以这个issue也就关闭了吧。
