### ISSUE TITLE
intentresolver keeps stopping

### ISSUE THREAD

**Issue by secretkit** [Xposed-Modules-Repo/com.alphi.actvityopenmanager#7]
Google pixel 9 pro, android 15, kernelsu, lsposed 1.10.1, 在很多场景点击分享都会闪退
![Screenshot_20241102-193244](https://github.com/user-attachments/assets/b9482538-60b1-42c4-ab31-2a9c43633941)

**Comment by alphime** [comment]
这个貌似跟我这个模块无关系吧？你试下取消激活模块还会这样吗

**Comment by secretkit** [comment]
> 这个貌似跟我这个模块无关系吧？你试下取消激活模块还会这样吗

确实不是这个模块的问题，打扰了，我再排查排查
